addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

language: cpp
compiler:
  - clang
  - gcc
before_script:
  - mkdir build
  - cd build
  - cmake ../src
script:
  - make
  - cd test
  - ./runUnitTests
