
# https://github.com/travis-ci/travis-ci/issues/7437
before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh
  - chmod +x cmake-3.7.2-Linux-x86_64.sh
  - ./cmake-3.7.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

language: cpp
compiler:
  - clang
  - gcc
before_script:
  - mkdir build
  - cd build
  - cmake ../src
script:
  - make
  - cd test
  - ./runUnitTests
